---
- name: Downloading phantomjs tar file
  sudo: no
  shell: "curl https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2 -o /home/vagrant/phantomjs-1.9.7-linux-x86_64.tar.bz2
 "
  args:
    creates: /home/vagrant/phantomjs-1.9.7-linux-x86_64.tar.bz2

- name: tar phantomjs
  sudo: no
  shell: "tar xjf /home/vagrant/phantomjs-1.9.7-linux-x86_64.tar.bz2"

- name: Installing phantomjs
  sudo: yes
  shell: "sudo ln -s /home/vagrant/phantomjs-1.9.7-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs"
  args:
    creates: /usr/local/share/phantomjs

  shell: "sudo ln -s /home/vagrant/phantomjs-1.9.7-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs"
  args:
    creates: /usr/local/bin/phantomjs

  shell: "sudo ln -s /home/vagrant/phantomjs-1.9.7-linux-x86_64/bin/phantomjs /usr/bin/phantomjs"
  args:
    creates: /usr/bin/phantomjs
