---
- name: Installing packages like curl, git, tree etc
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - ack
      - curl
      - git
      - make
      - tree
      - nodejs
      - build-essential
      - libxslt-dev
      - libxml2-dev
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev
