---
- name: Installing packages like curl, git, tree etc
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - ack
      - curl
      - git
      - make
      - tree
      - memcached
      - nodejs
      - build-essential
      - libxslt-dev
      - libxml2-dev
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev

- name: Installing heroku toolbelt
  sudo: no
  shell: "wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh"
