---
- name: Customizing git
  sudo: no
  action: shell git config --global {{ item }}
  with_items:
    - alias.co checkout
    - color.branch auto
    - color.diff auto
    - color.interactive auto
    - color.status auto
    - branch.autosetuprebase always
    - push.default current
    - core.mergeoptions --no-edit
    - color.status always
    - color.ui auto
