---
- name: Customizing git
  sudo: no
  shell: git config --global alias.co checkout
  shell: git config --global color.branch auto
  shell: git config --global color.diff auto
  shell: git config --global color.interactive auto
  shell: git config --global color.status auto
  shell: git config --global branch.autosetuprebase always
  shell: git config --global push.default current
  shell: git config --global core.mergeoptions --no-edit
  shell: git config color.status always
