---
- name: Customizing git
  sudo: no
  action: shell git config --global {{ item }}
  with_items:
    - alias.co checkout
    - color.branch auto
    - color.diff auto
    - color.interactive auto
    - color.status auto
    - branch.autosetuprebase always
    - push.default current
    - core.mergeoptions --no-edit
    - color.status always
    - color.ui auto

- name: Setting up git global username
  sudo: no
  shell: git config --global user.name '{{ git.config_username }}'

- name: Setting up git global email
  sudo: no
  shell: git config --global user.email '{{ git.config_email }}'
