---
# This playbook knows how to install postgres and its related extensions on Ubuntu

- hosts: all
  sudo: yes
  roles:
    - { role: packages_ubuntu }
    - { role: ruby }
    - { role: phantomjs }
    - { role: customize_git }
    - { role: customize_bash }
    - { role: postgres}
